services:
  app:
    build:
      context: .github/container
      dockerfile: Containerfile
    container_name: memes
    restart: unless-stopped
    volumes:
      - ./memes:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memes.rule=Host(`memes.hpi.church`)"
      - "traefik.http.routers.memes.entrypoints=websecure"
      - "traefik.http.routers.memes.tls.certResolver=letsencrypt"
      - "traefik.http.routers.memes.service=memes"
      - "traefik.http.services.memes.loadbalancer.server.port=80"
